baseURL = "https://kiera.akagi.moe/"
languageCode = "en-us"
title = "kiera"
theme = "smol"
copyright = "Kiera Akagi"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[params]
    subtitle = "utterly Deranged anime girl on the internet"
    dateFmt = "2006.01.02 15:04"

[menu]
  [[menu.main]]
        identifier = "posts"
        name = "posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "tags"
        url = "/tags/"
        weight = 3
        
  [[menu.main]]
        identifier = "about"
        name = "about"
        url = "/about/"
        weight = 4

  [[menu.footer]]
        name = "PGP key"
        url = "/pgp/4220e5624ba048ad5cc3765e00e6778c91ff0d5a.asc"
        weight = 1 

  [[menu.footer]]
        name = "git"
        url = "https://git.nab.moe/"
        weight = 2 
